In [3]:
import pandas as pd
import os
os.chdir('C:\\Users\\Administrator\\Desktop\\JC数据集')

In [9]:
#读取EXCEL格式文件
df= pd.read_excel('流量练习数据.xls')
df

   流量来源 来源明细    访客数   支付转化率     客单价
0    一级   -A  35188  0.0998   54.30
1    一级   -B  28467  0.1127   99.93
2    一级   -C  13747  0.0254    0.08
3    一级   -D   5183  0.0247   37.15
4    一级   -E   4361  0.0431   91.73
5    一级   -F   4063  0.1157   65.09
6    一级   -G   2122  0.1027   86.45
7    一级   -H   2041  0.0706   44.07
8    一级   -I   1991  0.1652  104.57
9    一级   -J   1981  0.0575   75.93
10   一级   -K   1958  0.1471   85.03
11   一级   -L   1780  0.1315   98.87
12   一级   -M   1447  0.0104   80.07
13   二级   -A  39048  0.1160   91.91
14   二级   -B   3316  0.0709   66.28
15   二级   -C   2043  0.0504   41.91
16   三级   -A  23140  0.0969   83.75
17   三级   -B  14813  0.2014   82.97
18   四级   -A    216  0.0185   94.25
19   四级   -B     31  0.0000     NaN
20   四级   -C     17  0.0000     NaN
21   四级   -D      3  0.0000     NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
流量来源     22 non-null object
来源明细     22 non-null object
访客数      22 non-null int64
支付转化率    22 non-null float64
客单价      19 non-null float64
dtypes: float64(2), int64(1), object(2)
memory usage: 960.0+ bytes

## 一、基于位置的索引

### 场景一：选择一级流量来源渠道的所有行

In [8]:
df.iloc[:13,:]

   流量来源 来源明细    访客数   支付转化率     客单价
0    一级   -A  35188  0.0998   54.30
1    一级   -B  28467  0.1127   99.93
2    一级   -C  13747  0.0254    0.08
3    一级   -D   5183  0.0247   37.15
4    一级   -E   4361  0.0431   91.73
5    一级   -F   4063  0.1157   65.09
6    一级   -G   2122  0.1027   86.45
7    一级   -H   2041  0.0706   44.07
8    一级   -I   1991  0.1652  104.57
9    一级   -J   1981  0.0575   75.93
10   一级   -K   1958  0.1471   85.03
11   一级   -L   1780  0.1315   98.87
12   一级   -M   1447  0.0104   80.07

### 场景二：把所有渠道的流量来源和客单价单拎出来看一看

In [11]:
df.iloc[:,[0,4]]

   流量来源     客单价
0    一级   54.30
1    一级   99.93
2    一级    0.08
3    一级   37.15
4    一级   91.73
5    一级   65.09
6    一级   86.45
7    一级   44.07
8    一级  104.57
9    一级   75.93
10   一级   85.03
11   一级   98.87
12   一级   80.07
13   二级   91.91
14   二级   66.28
15   二级   41.91
16   三级   83.75
17   三级   82.97
18   四级   94.25
19   四级     NaN
20   四级     NaN
21   四级     NaN

### 场景三：我们想要看一看二级、三级流量来源、来源明细对应的访客和转化

In [13]:
df.iloc[13:18,0:4]

   流量来源 来源明细    访客数   支付转化率
13   二级   -A  39048  0.1160
14   二级   -B   3316  0.0709
15   二级   -C   2043  0.0504
16   三级   -A  23140  0.0969
17   三级   -B  14813  0.2014

## 二、基于条件的索引

#### 判断返回的结果

In [14]:
df['流量来源'] == '一级'

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
Name: 流量来源, dtype: bool

### 场景一：选择一级渠道的所有行

In [15]:
df.loc[df['流量来源'] == '一级',:]

   流量来源 来源明细    访客数   支付转化率     客单价
0    一级   -A  35188  0.0998   54.30
1    一级   -B  28467  0.1127   99.93
2    一级   -C  13747  0.0254    0.08
3    一级   -D   5183  0.0247   37.15
4    一级   -E   4361  0.0431   91.73
5    一级   -F   4063  0.1157   65.09
6    一级   -G   2122  0.1027   86.45
7    一级   -H   2041  0.0706   44.07
8    一级   -I   1991  0.1652  104.57
9    一级   -J   1981  0.0575   75.93
10   一级   -K   1958  0.1471   85.03
11   一级   -L   1780  0.1315   98.87
12   一级   -M   1447  0.0104   80.07

### 场景二：我们想要把所有渠道的流量来源和客单价单拎出来看一看

In [16]:
df.loc[:,['流量来源','客单价']]

   流量来源     客单价
0    一级   54.30
1    一级   99.93
2    一级    0.08
3    一级   37.15
4    一级   91.73
5    一级   65.09
6    一级   86.45
7    一级   44.07
8    一级  104.57
9    一级   75.93
10   一级   85.03
11   一级   98.87
12   一级   80.07
13   二级   91.91
14   二级   66.28
15   二级   41.91
16   三级   83.75
17   三级   82.97
18   四级   94.25
19   四级     NaN
20   四级     NaN
21   四级     NaN

### 场景三：我们想要提取二级、三级流量来源、来源明细对应的访客和转化。

In [17]:
df.loc[df['流量来源'].isin(['二级','三级']),['流量来源','来源明细','访客数','支付转化率']]

   流量来源 来源明细    访客数   支付转化率
13   二级   -A  39048  0.1160
14   二级   -B   3316  0.0709
15   二级   -C   2043  0.0504
16   三级   -A  23140  0.0969
17   三级   -B  14813  0.2014

#### 列的聚合函数

In [28]:
df['访客数'].mean()    #计算均值
df['访客数'].std()     #计算标准差
df['访客数'].median()  #计算中位数
df['访客数'].max()     #计算最大值
df['访客数'].min()     #计算最小值

print('访客数均值：',df['访客数'].mean())
print('转化率均值：',df['支付转化率'].mean())
print('客单价均值：',df['客单价'].mean())

访客数均值： 8498.0
转化率均值： 0.0754772727273
客单价均值： 72.86

### 场景四：对于流量渠道的数据，我们真正感兴趣的是优质渠道，有哪些渠道的访客数、转化率、客单价都高于平均值呢？他的销售占比又是怎么样的呢？

#### 判断单列是否大于均值

In [29]:
df['访客数'] > df['访客数'].mean()

0      True
1      True
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16     True
17     True
18    False
19    False
20    False
21    False
Name: 访客数, dtype: bool

#### 判断是否同时大于均值

In [31]:
(df['访客数'] > df['访客数'].mean()) & (df['支付转化率'] > df['支付转化率'].mean()) & (df['客单价'] > df['客单价'].mean())

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16     True
17     True
18    False
19    False
20    False
21    False
dtype: bool

#### 基于判断结果，筛选出我们希望的优质渠道

In [32]:
df.loc[(df['访客数'] > df['访客数'].mean()) & 
      (df['支付转化率'] > df['支付转化率'].mean()) & 
      (df['客单价'] > df['客单价'].mean()),:]

   流量来源 来源明细    访客数   支付转化率    客单价
1    一级   -B  28467  0.1127  99.93
13   二级   -A  39048  0.1160  91.91
16   三级   -A  23140  0.0969  83.75
17   三级   -B  14813  0.2014  82.97